---
- name: "Run parse-google-sheets Role"
  hosts: all
  tasks:
  - name: add Python modules
    ansible.builtin.pip:
      name:
        # - json
        - httplib2
        - google-api-python-client
      extra_args: --upgrade
    delegate_to: localhost
    run_once: true

  - name: "Run the parse-google-sheets role"
    include_role:
      name: parse-google-sheets
